version: "3.7"

services:
  freetds-dev:
    image: blieusong/freetds-dev-c
    hostname: freetds-dev-c
    working_dir: /workspace
    volumes:
      - ./config/freetds.conf:/usr/local/etc/freetds.conf
      # workspace
      - ${HOME}/docker/workspace/:/workspace/
      # Bring Git setup to the container
      - ${HOME}/.gitconfig:/root/.gitconfig
      # Keep bash history 
      - ${HOME}/docker/config/.bash_history:/root/.bash_history
      # Keep VSCode's plugin
      - ${HOME}/docker/config/.vscode-server:/root/.vscode-server
    networks:
      tds-bridge:
    # to enable gdb
    cap_add: 
      - SYS_PTRACE
    tty: true

  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: mssql-server
    environment:
      - MSSQL_SA_PASSWORD=micro50ft!
      - MSSQL_LCID=1033
      - MSSQL_COLLATION=Latin1_General_100_BIN2
      - MSSQL_MEMORY_LIMIT_MB=4096
      - MSSQL_BACKUP_DIR=/var/opt/mssql/data/
      - MSSQL_DATA_DIR=/var/opt/mssql/data/
      - MSSQL_LOG_DIR=/var/opt/mssql/data/
      - MSSQL_DUMP_DIR=/var/opt/mssql/data/
      - ACCEPT_EULA=y
      - MSSQL_ENABLE_AGENT=false
    volumes:
      - $HOME/dbdata/mssql/:/var/opt/mssql/data
    user: "root:root"
    networks:
      tds-bridge:
    ports:
      - 1433:1433
    tty: true
  
  ase-server:
    image: blieusong/sybase-ase
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - $HOME/dbdata/sybase/data:/data
    networks:
      tds-bridge:
    ports:
      - 5000:5000
    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

networks:
  tds-bridge:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"